/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeddingIndexImport } from './routes/wedding/index'
import { Route as CookbookIndexImport } from './routes/cookbook/index'
import { Route as CookbookRecipesWalnutPastaImport } from './routes/cookbook/recipes/walnut-pasta'
import { Route as CookbookRecipesSmokyBlackBeanGrilledCheeseImport } from './routes/cookbook/recipes/smoky-black-bean-grilled-cheese'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeddingIndexRoute = WeddingIndexImport.update({
  id: '/wedding/',
  path: '/wedding/',
  getParentRoute: () => rootRoute,
} as any)

const CookbookIndexRoute = CookbookIndexImport.update({
  id: '/cookbook/',
  path: '/cookbook/',
  getParentRoute: () => rootRoute,
} as any)

const CookbookRecipesWalnutPastaRoute = CookbookRecipesWalnutPastaImport.update(
  {
    id: '/cookbook/recipes/walnut-pasta',
    path: '/cookbook/recipes/walnut-pasta',
    getParentRoute: () => rootRoute,
  } as any,
)

const CookbookRecipesSmokyBlackBeanGrilledCheeseRoute =
  CookbookRecipesSmokyBlackBeanGrilledCheeseImport.update({
    id: '/cookbook/recipes/smoky-black-bean-grilled-cheese',
    path: '/cookbook/recipes/smoky-black-bean-grilled-cheese',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookIndexImport
      parentRoute: typeof rootRoute
    }
    '/wedding/': {
      id: '/wedding/'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingIndexImport
      parentRoute: typeof rootRoute
    }
    '/cookbook/recipes/smoky-black-bean-grilled-cheese': {
      id: '/cookbook/recipes/smoky-black-bean-grilled-cheese'
      path: '/cookbook/recipes/smoky-black-bean-grilled-cheese'
      fullPath: '/cookbook/recipes/smoky-black-bean-grilled-cheese'
      preLoaderRoute: typeof CookbookRecipesSmokyBlackBeanGrilledCheeseImport
      parentRoute: typeof rootRoute
    }
    '/cookbook/recipes/walnut-pasta': {
      id: '/cookbook/recipes/walnut-pasta'
      path: '/cookbook/recipes/walnut-pasta'
      fullPath: '/cookbook/recipes/walnut-pasta'
      preLoaderRoute: typeof CookbookRecipesWalnutPastaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookIndexRoute
  '/wedding': typeof WeddingIndexRoute
  '/cookbook/recipes/smoky-black-bean-grilled-cheese': typeof CookbookRecipesSmokyBlackBeanGrilledCheeseRoute
  '/cookbook/recipes/walnut-pasta': typeof CookbookRecipesWalnutPastaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookIndexRoute
  '/wedding': typeof WeddingIndexRoute
  '/cookbook/recipes/smoky-black-bean-grilled-cheese': typeof CookbookRecipesSmokyBlackBeanGrilledCheeseRoute
  '/cookbook/recipes/walnut-pasta': typeof CookbookRecipesWalnutPastaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/wedding/': typeof WeddingIndexRoute
  '/cookbook/recipes/smoky-black-bean-grilled-cheese': typeof CookbookRecipesSmokyBlackBeanGrilledCheeseRoute
  '/cookbook/recipes/walnut-pasta': typeof CookbookRecipesWalnutPastaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/wedding'
    | '/cookbook/recipes/smoky-black-bean-grilled-cheese'
    | '/cookbook/recipes/walnut-pasta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookbook'
    | '/wedding'
    | '/cookbook/recipes/smoky-black-bean-grilled-cheese'
    | '/cookbook/recipes/walnut-pasta'
  id:
    | '__root__'
    | '/'
    | '/cookbook/'
    | '/wedding/'
    | '/cookbook/recipes/smoky-black-bean-grilled-cheese'
    | '/cookbook/recipes/walnut-pasta'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
  WeddingIndexRoute: typeof WeddingIndexRoute
  CookbookRecipesSmokyBlackBeanGrilledCheeseRoute: typeof CookbookRecipesSmokyBlackBeanGrilledCheeseRoute
  CookbookRecipesWalnutPastaRoute: typeof CookbookRecipesWalnutPastaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookIndexRoute: CookbookIndexRoute,
  WeddingIndexRoute: WeddingIndexRoute,
  CookbookRecipesSmokyBlackBeanGrilledCheeseRoute:
    CookbookRecipesSmokyBlackBeanGrilledCheeseRoute,
  CookbookRecipesWalnutPastaRoute: CookbookRecipesWalnutPastaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cookbook/",
        "/wedding/",
        "/cookbook/recipes/smoky-black-bean-grilled-cheese",
        "/cookbook/recipes/walnut-pasta"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cookbook/": {
      "filePath": "cookbook/index.tsx"
    },
    "/wedding/": {
      "filePath": "wedding/index.tsx"
    },
    "/cookbook/recipes/smoky-black-bean-grilled-cheese": {
      "filePath": "cookbook/recipes/smoky-black-bean-grilled-cheese.tsx"
    },
    "/cookbook/recipes/walnut-pasta": {
      "filePath": "cookbook/recipes/walnut-pasta.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
