/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WeddingIndexImport } from './routes/wedding/index'
import { Route as CookbookIndexImport } from './routes/cookbook/index'
import { Route as CookbookRecipeNameImport } from './routes/cookbook/$recipeName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WeddingIndexRoute = WeddingIndexImport.update({
  id: '/wedding/',
  path: '/wedding/',
  getParentRoute: () => rootRoute,
} as any)

const CookbookIndexRoute = CookbookIndexImport.update({
  id: '/cookbook/',
  path: '/cookbook/',
  getParentRoute: () => rootRoute,
} as any)

const CookbookRecipeNameRoute = CookbookRecipeNameImport.update({
  id: '/cookbook/$recipeName',
  path: '/cookbook/$recipeName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cookbook/$recipeName': {
      id: '/cookbook/$recipeName'
      path: '/cookbook/$recipeName'
      fullPath: '/cookbook/$recipeName'
      preLoaderRoute: typeof CookbookRecipeNameImport
      parentRoute: typeof rootRoute
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookIndexImport
      parentRoute: typeof rootRoute
    }
    '/wedding/': {
      id: '/wedding/'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook/$recipeName': typeof CookbookRecipeNameRoute
  '/cookbook': typeof CookbookIndexRoute
  '/wedding': typeof WeddingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook/$recipeName': typeof CookbookRecipeNameRoute
  '/cookbook': typeof CookbookIndexRoute
  '/wedding': typeof WeddingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cookbook/$recipeName': typeof CookbookRecipeNameRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/wedding/': typeof WeddingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookbook/$recipeName' | '/cookbook' | '/wedding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookbook/$recipeName' | '/cookbook' | '/wedding'
  id: '__root__' | '/' | '/cookbook/$recipeName' | '/cookbook/' | '/wedding/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRecipeNameRoute: typeof CookbookRecipeNameRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
  WeddingIndexRoute: typeof WeddingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRecipeNameRoute: CookbookRecipeNameRoute,
  CookbookIndexRoute: CookbookIndexRoute,
  WeddingIndexRoute: WeddingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cookbook/$recipeName",
        "/cookbook/",
        "/wedding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cookbook/$recipeName": {
      "filePath": "cookbook/$recipeName.tsx"
    },
    "/cookbook/": {
      "filePath": "cookbook/index.tsx"
    },
    "/wedding/": {
      "filePath": "wedding/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
